apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-github-https-credentials.yaml
- base/projects/core.yaml
- base/projects/apps.yaml
- base/projects/monitoring.yaml
- base/projects/networking.yaml
- base/core/namespaces.yaml
- base/core/argocd.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesJson6902:
- path: overlay/deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argo
images:
- name: quay.io/argoproj/argocd
  newTag: v2.5.3

configMapGenerator:
  - envs:
      - overlay/nogpg.yaml